language: python

python:
  - "2.7"
  - "2.6"

install:
  - pip install coveralls 
  - pip install -r requirements.txt
  - python setup.py install

script:
  - python setup.py nosetests

after_success:
  - coveralls
